leftnav:
- identifier: 7e1b54de-e612-7afd-d01e-4f6cd14fcae2
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9877e6f8-5c59-20e9-014b-efbb4974d516
  name: Study Materials
  url: /pages/study-materials
  weight: 20
- identifier: b59d2755-2347-0682-9e3a-24e5519f79f0
  name: Audio Lectures
  url: /video_galleries/audio-lectures
  weight: 30
- identifier: 04e3e79b-63d9-a5b7-8d34-739dfbf35194
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: dbf93c5e-37a0-5ba4-06f2-75eeb0f1e306
  name: Related Resources
  url: /pages/related-resources
  weight: 50
